### ISSUE TITLE
USER STORY: Set list status private or public

### ISSUE THREAD

**Issue by BjornL1** [BjornL1/to_the_list_gd2#11]
As a Site User, I can set my lists to be private or public so that I can control whether I want to share my lists and letting other users adding items to my public list.

### Acceptance Criteria:

a. When the user is logged in, it shall be possible to change the status with an switch button
b. When the user changes the status it shall be clearly visible in  which status the list is in.

### Tasks

- [x] Add a toggle switch button in the html template holding the lists
- [x] Add function to display different status and ensure database connection to display correct status when a user has logged in.
- [x] Add a function that does not display the toggle switch if the logged in user is not the owner of the public list.
