### ISSUE TITLE
USER STORY: Add and view items.

### ISSUE THREAD

**Issue by BjornL1** [BjornL1/to_the_list_gd2#13]
As a Site User, I create and view items to a list so that I can easily store and find my items.

### Acceptance Criteria:

a. When the user is logged in, the "add items" button shall be present but integrated with showing lists.

### Tasks

- [x] Add a button to add items when user clicks a list.
- [x] Create HTML to enable the user to enter a name for the new item.
- [x] Create HTML for showing a confirmation message to the user for the newly created item
- [x] Update functions and URLs to enable the HTML files to be rendered correctly.
