### ISSUE TITLE
USER STORY: Delete items

### ISSUE THREAD

**Issue by BjornL1** [BjornL1/to_the_list_gd2#15]
As a Site User, I can delete items so that I can remove ones that are no longer needed.

### Acceptance Criteria:

a. When the user is logged in, a delete option shall be accessible (for items owned by the logged in user) via an edit button connected to each item in a list which 
b. When the user uses the edit button, the delete item option shall be presented.

### Tasks

- [x] For item owners: Add an edit button for each item presented in the list view.
- [x] Add a delete button for the separate edit view.
- [x] Add a message function to let the user confirm deletion.
- [x] Create HTML to show the option for deleting the item.
- [x] Create HTML for showing a confirmation message displaying the deletion and a close button.
- [x] Update functions, URLs, and models to enable the HTML files to be rendered correctly.
