### ISSUE TITLE
USER STORY: Duplicate item

### ISSUE THREAD

**Issue by BjornL1** [BjornL1/to_the_list_gd2#16]
As a Site User, I can view and copy an existing list created by another user so that I can reuse items in my own lists.

### Acceptance Criteria:

a. When the user is logged in, it shall be possible to duplicate item on two ways:
a.1 If user is owning the item the duplicate shall be reached via an edit button 
a.2 If user is not owning the item, the clone button will be displayed instead of an edit button.

### Tasks

- [x] Add an edit button for logged in users owning the button, display duplicate in separate view.
- [x] Add a clone button logged in users not owning the button, display duplicate in view but limited to duplicate.
- [x] Add a message function to let the user confirm duplication.
- [x] Create HTML to show a new name to be entered for the cloned item.
- [x] Update functions to check if the logged-in user is the owner of the list, update URLs, and models to enable the HTML files to be rendered correctly.
