### ISSUE TITLE
USER STORY: Register account

### ISSUE THREAD

**Issue by BjornL1** [BjornL1/to_the_list_gd2#2]
As a Site User, I can register an account so that I can create, read, update and delete my lists and items.

Acceptance Criteria:
a. A signup button should be visible on the homepage.
b. When I click the button I should be taken to the signup page.
c. When I fill in my details and click submit a new account should be created for me.
d. I should then be notified that I have been logged in.

### Tasks
- [x] Install allauth and add to installed apps
- [x] Add allauth urls
- [x] Add signup link to navbar and home page
- [x]  Customise allauth signup form HTML templates
- [x] Create message to notify user of successful signup
