### ISSUE TITLE
USER STORY: User experience first time interaction

### ISSUE THREAD

**Issue by BjornL1** [BjornL1/to_the_list_gd2#5]
As a Site User, I can immediately understand the purpose of the site so that I can decide if it meets my needs.

### Acceptance Criteria:

a. When the user lands on the home page, there shall be a description and an image illustrating the purpose of the site.
b. The user shall be able to reach a "Learn" section directly from the home page.
c. The user shall be able to start creating a list immediately from the landing page view, which will lead to user registration and login.

### Tasks

- [x] Add a short description and an image illustrating the purpose of the site.
- [x] Create an HTML page with a description of the site and add a link to it in the navbar section.
- [x] Add a button with the possibility to create a list directly from the home page.
