### ISSUE TITLE
USER STORY: Navigate items to lists

### ISSUE THREAD

**Issue by BjornL1** [BjornL1/to_the_list_gd2#6]
As a Site User, I can view which items belong to each list so that I don't misunderstand which items belong to which list.

### Acceptance Criteria:

a. When the user is logged in, the shared lists shall be clearly visible with a heading describing them as shared lists.
b. The user shall see the items for each list by clicking on the list name that is displayed.
c. Implement pagination to improve visibility for user lists and other lists.

### Tasks

- [x] Add a function to expand items under each list.
- [x] Add a function to allow scrolling in the items belonging to each list.
- [x] Add pagination control for both logged-in user lists and shared lists

**Comment by BjornL1** [comment]
Update the task with pagination feedback to enhance user intuition and navigation.
