### ISSUE TITLE
USER STORY: Create lists

### ISSUE THREAD

**Issue by BjornL1** [BjornL1/to_the_list_gd2#7]
As a Site User, I can add and view items to a list so that I can easily store and find my items.

### Acceptance Criteria:

a. When the user is not logged in, a button shall be accessible to create lists.
b. When the user is logged in, the "create new list" button shall be present but integrated with showing lists.

### Tasks

- [x] Add a button on the landing page to create a new list.
- [x] Create HTML to enable the user to enter a name for the new list.
- [x] Create HTML for showing a confirmation message to the user for the newly created list.
- [x] Update functions and URLs to enable the HTML files to be rendered correctly.
