### ISSUE TITLE
USER STORY: Rename lists

### ISSUE THREAD

**Issue by BjornL1** [BjornL1/to_the_list_gd2#8]
As a Site User, I can rename a list so that I don't need to delete and recreate a new list if I accidentally named it wrong.

### Acceptance Criteria:

a. When the user is logged in, a rename option shall be accessible via an edit button connected to each list.
b. When the user uses the edit button, the rename list option shall be presented.

### Tasks

- [x] Add an edit button for each list presented in the shopping list view.
- [x] Add a rename button for the separate edit view.
- [x] Create HTML to show the option for renaming the list.
- [x] Create HTML for showing a confirmation message displaying the new name and a close button.
- [x] Update functions, URLs, and models to enable the HTML files to be rendered correctly.
