### ISSUE TITLE
USER STORY: View and copy lists

### ISSUE THREAD

**Issue by BjornL1** [BjornL1/to_the_list_gd2#9]
As a Site User, I can view and copy an existing list created by another user so that I can reuse items in my own lists.

### Acceptance Criteria:

a. When the user is logged in, it shall be possible to view public lists added by other users.
b. It shall be possible for the logged-in user to see which lists are owned by others.
c. It shall be possible to clone another user's public list.
d. When a user has cloned a list, the logged-in user will be the owner of the cloned list.

### Tasks

- [x] Add a clone button for each list presented in the shopping list view that is public and owned by another user.
- [x] Add an indicator on the list that displays whether the logged-in user owns it or not.
- [x] Add a message function to let the user confirm cloning.
- [x] Create HTML to show a new name to be entered for the cloned list.
- [x] Create HTML for showing a confirmation message displaying the new name of the new cloned list.
- [x] Update functions to check if the logged-in user is the owner of the list, update URLs, and models to enable the HTML files to be rendered correctly.
